In [1]:
#1-DIMENSIONAL DATA STRUCTURE
import pandas as pd
s=pd.Series([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64

In [3]:
#2-DIMENSIONAL DATA STRUCTURE
data={
    "Name":["Anya","Babita","Carry"],
    "Marks":[80,90,85],
}
df=pd.DataFrame(data)
print(df)

     Name  Marks
0    Anya     80
1  Babita     90
2   Carry     85

In [4]:
df.head()
df.tail()

     Name  Marks
0    Anya     80
1  Babita     90
2   Carry     85

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [8]:
df.describe()

       Marks
count    3.0
mean    85.0
std      5.0
min     80.0
25%     82.5
50%     85.0
75%     87.5
max     90.0

In [10]:
df["Marks"]

0    80
1    90
2    85
Name: Marks, dtype: int64

In [12]:
df[["Name","Marks"]]

     Name  Marks
0    Anya     80
1  Babita     90
2   Carry     85

In [13]:
df.loc[1]
df.iloc[1]

Name     Babita
Marks        90
Name: 1, dtype: object

In [15]:
df["Grade"]=["B","A","B"]
print(df)

     Name  Marks Grade
0    Anya     80     B
1  Babita     90     A
2   Carry     85     B

In [16]:
df.loc[1,"Marks"]=95
print(df)

     Name  Marks Grade
0    Anya     80     B
1  Babita     95     A
2   Carry     85     B

In [17]:
df.drop("Grade",axis=1)

     Name  Marks
0    Anya     80
1  Babita     95
2   Carry     85

In [18]:
df.drop(1,axis=0)

    Name  Marks Grade
0   Anya     80     B
2  Carry     85     B

In [19]:
df.isnull()

    Name  Marks  Grade
0  False  False  False
1  False  False  False
2  False  False  False

In [20]:
df.dropna()

     Name  Marks Grade
0    Anya     80     B
1  Babita     95     A
2   Carry     85     B

In [21]:
df.fillna(0)

     Name  Marks Grade
0    Anya     80     B
1  Babita     95     A
2   Carry     85     B

In [23]:
df.sort_values("Marks")

     Name  Marks Grade
0    Anya     80     B
2   Carry     85     B
1  Babita     95     A

In [24]:
df.sort_values("Marks",ascending=False)

     Name  Marks Grade
1  Babita     95     A
2   Carry     85     B
0    Anya     80     B

In [25]:
import pandas as pd
data={
     "Name":["Anya","Babita","Carry"],
    "Marks":[80,90,85],
}
df=pd.DataFrame(data)
print(df)
df["Age"]=[20,21,19]
print(df)
df["Result"]="Pass"
print(df)
df["Bonus"]=df["Marks"]+5
print(df)

     Name  Marks
0    Anya     80
1  Babita     90
2   Carry     85
     Name  Marks  Age
0    Anya     80   20
1  Babita     90   21
2   Carry     85   19
     Name  Marks  Age Result
0    Anya     80   20   Pass
1  Babita     90   21   Pass
2   Carry     85   19   Pass
     Name  Marks  Age Result  Bonus
0    Anya     80   20   Pass     85
1  Babita     90   21   Pass     95
2   Carry     85   19   Pass     90